server:
  port: 8082


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: QWERTY@123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE


# Eureka Client Configuration
eureka:
  instance:
    prefer-ip-address: true
    appname: HOTEL-SERVICE

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka